import type { UserHandle } from "./models";

export const TWITTER_HANELE_COMPLETIONS: UserHandle[] = [
	{ username: "ThePrimeagen", handle: "@ThePrimeagen" },
	{ username: "TJ DeVries", handle: "@Tjdervies" },
	{ username: "Effect TS", handle: "@EffectTS_" },
	{ username: "Dillan Mulroy", handle: "@dillanmulroy" },
	{ username: "Kent C. Dodds", handle: "@kentcdodds" },
	{ username: "Dan Abramov", handle: "@dan_abramov" },
	{ username: "Addy Osmani", handle: "@addyosmani" },
	{ username: "Wes Bos", handle: "@wesbos" },
	{ username: "Sarah Drasner", handle: "@sarah_edo" },
	{ username: "Linus Tech", handle: "@LinusTech" },
	{ username: "Fireship", handle: "@fireship_dev" },
	{ username: "Chris Coyier", handle: "@chriscoyier" },
	{ username: "Una Kravets", handle: "@una" },
	{ username: "Jake Archibald", handle: "@jaffathecake" },
	{ username: "Evan You", handle: "@youyuxi" },
	{ username: "Ryan Florence", handle: "@ryanflorence" },
	{ username: "Adam Wathan", handle: "@adamwathan" },
	{ username: "Guillermo Rauch", handle: "@rauchg" },
	{ username: "Lea Verou", handle: "@leaverou" },
	{ username: "Brad Frost", handle: "@brad_frost" },
	{ username: "Cassidy Williams", handle: "@cassidoo" },
	{ username: "Sentry", handle: "@getsentry" },
	{ username: "Lee Robinson", handle: "@lee_rob" },
	{ username: "Tania Rascia", handle: "@taniarascia" },
	{ username: "Ben Awad", handle: "@benawad" },
	{ username: "Theo Browne", handle: "@t3dotgg" },
	{ username: "Thorsten Ball", handle: "@thorstenball" },
	{ username: "HTMX", handle: "@htmx_org" },
	{ username: "Swyx", handle: "@swyx" },
	{ username: "Ania Kubow", handle: "@ania_kubow" },
	{ username: "David Walsh", handle: "@davidwalshblog" },
	{ username: "Sindre Sorhus", handle: "@sindresorhus" },
	{ username: "Emma Bostian", handle: "@emmabostian" },
	{ username: "Max Lynch", handle: "@maxlynch" },
	{ username: "Rich Harris", handle: "@Rich_Harris" },
	{ username: "Monica Lent", handle: "@monicalent" },
	{ username: "Hacker News", handle: "@newsycombinator" },
	{ username: "Tailwind CSS", handle: "@tailwindcss" },
	{ username: "Vercel", handle: "@vercel" },
	{ username: "Netlify", handle: "@netlify" },
	{ username: "Svelte", handle: "@sveltejs" },
	{ username: "Minko Gechev", handle: "@mgechev" },
	{ username: "Sam Selikoff", handle: "@samselikoff" },
	{ username: "Josh Comeau", handle: "@joshwcomeau" },
	{ username: "Chloe Condon", handle: "@ChloeCondon" },
	{ username: "TypeScript", handle: "@typescript" },
	{ username: "Deno", handle: "@deno_land" },
	{ username: "Ryan Carniato", handle: "@RyanCarniato" },
	{ username: "Prettier", handle: "@PrettierCode" },
	{ username: "Jack Herrington", handle: "@jherr" },
] as const;
